[tools]
deno = "2.6.5"
go = "1.25.5"
node = "25.2.1"
python = "3.14.2"
rust = "1.92.0"
uv = "0.9.21"
# node製tools
"npm:atcoder-cli" = "2.2.0"
"npm:markdownlint-cli2" = "0.20.0"
"npm:pyright" = "1.1.407"
"npm:typescript-language-server" = "5.1.3"
"npm:@devcontainers/cli" = "0.80.3"
"npm:yaml-language-server" = "1.19.2"
"npm:eslint" = "9.39.2"
# python製tools
"pipx:terminaltexteffects" = "0.14.2"
usage = "2.11.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.pipx]
uvx = true

[settings.python]
compile = true
