[tools]
deno = "2.5.6"
go = "1.25.4"
node = "24.11.1"
python = "3.14.0"
rust = "1.91.1"
uv = "0.9.10"
# node製tools
"npm:atcoder-cli" = "2.2.0"
"npm:markdownlint-cli2" = "0.19.1"
"npm:pyright" = "1.1.407"
"npm:typescript-language-server" = "5.1.3"
"npm:@devcontainers/cli" = "0.80.2"
"npm:yaml-language-server" = "1.19.2"
"npm:eslint" = "9.39.1"
# python製tools
"pipx:terminaltexteffects" = "0.13.0"
lua = "5.4.8"
usage = "2.8.0"
"aqua:astral-sh/ruff" = "0.14.7"
"aqua:LuaLS/lua-language-server" = "3.16.0"
"ubi:hidehic0/acc_utils" = { version = "0.0.7", exe = "acc_utils" }

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.pipx]
uvx = true

[settings.python]
compile = true
